[profile]

[profile.dioxus-wasm]
inherits = "dev"
opt-level = 2

[profile.dioxus-server]
inherits = "dev"

[profile.dioxus-android]
inherits = "dev"

[registries.ycrates]
index = "sparse+https://crates.ycode.pl/api/v1/crates/"
credential-provider = ["cargo:token"]
